name: ADN
version: "${version}"
main: com.bunubbv.adn.adn
api-version: '1.19'
author: bunubbv
website: "https://github.com/bunubbv/ADN"
commands:
  adn:
    usage: '/adn'
permissions:
  adn.format:
    default: true
  adn.reload:
    default: op
  adn.remove:
    default: true
  adn.reset.self:
    default: true
  adn.reset.user:
    default: op
  adn.set.self:
    default: true
  adn.set.user:
    default: op
  adn.use:
    default: true
softdepend:
  - ProtocolLib
